/**
 * API-Only Generator
 * Generates just the typed API client and types for the project
 */

const clientGenerator = require('./client');
const typesGenerator = require('./types');
const webhooksGenerator = require('./webhooks');

class ApiOnlyGenerator {
  /**
   * Generate API-only files
   * @param {Object} options - Generation options
   * @returns {Promise<Object>} - Generated file paths
   */
  async generate(options) {
    const results = {
      client: null,
      types: null,
      webhooks: null,
      index: null,
    };

    // Generate TypeScript types first (used by client)
    results.types = await typesGenerator.generate(options);

    // Generate the typed API client
    results.client = await clientGenerator.generate(options);

    // Generate webhook utilities
    results.webhooks = await webhooksGenerator.generate(options);

    // Generate index file
    results.index = await this.generateIndex(options);

    return results;
  }

  /**
   * Generate index.ts/js that exports everything
   */
  async generateIndex(options) {
    const { projectPath, isTypeScript } = options;
    const fs = require('fs');
    const path = require('path');
    const { ensureDir, writeFileWithBackup, checkFileOverwrite } = require('../../utils/file-utils');

    // Determine output directory
    let outputDir;
    if (fs.existsSync(path.join(projectPath, 'src'))) {
      outputDir = path.join(projectPath, 'src', 'lib', 'l4yercak3');
    } else {
      outputDir = path.join(projectPath, 'lib', 'l4yercak3');
    }

    ensureDir(outputDir);

    const extension = isTypeScript ? 'ts' : 'js';
    const outputPath = path.join(outputDir, `index.${extension}`);

    const action = await checkFileOverwrite(outputPath);
    if (action === 'skip') {
      return null;
    }

    const content = isTypeScript
      ? `/**
 * L4YERCAK3 API Client
 * Auto-generated by @l4yercak3/cli
 */

export { L4yercak3Client, getL4yercak3Client, L4yercak3Error } from './client';
export type * from './types';
export { verifyWebhookSignature, type WebhookEvent } from './webhooks';
`
      : `/**
 * L4YERCAK3 API Client
 * Auto-generated by @l4yercak3/cli
 */

const { L4yercak3Client, getL4yercak3Client, L4yercak3Error } = require('./client');
const { verifyWebhookSignature } = require('./webhooks');

module.exports = {
  L4yercak3Client,
  getL4yercak3Client,
  L4yercak3Error,
  verifyWebhookSignature,
};
`;

    return writeFileWithBackup(outputPath, content, action);
  }
}

module.exports = new ApiOnlyGenerator();
