/**
 * File Utilities
 * Helper functions for safe file operations
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const inquirer = require('inquirer');
const chalk = require('chalk');

const GENERATED_HEADER = 'Auto-generated by @l4yercak3/cli';

/**
 * Check if a file was generated by our CLI
 */
function isGeneratedFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return false;
  }

  try {
    const content = fs.readFileSync(filePath, 'utf8');
    // Check first 500 chars for our header
    return content.substring(0, 500).includes(GENERATED_HEADER);
  } catch (error) {
    return false;
  }
}

/**
 * Check if file exists and prompt for action if needed
 * Returns: 'write' | 'skip' | 'backup'
 */
async function checkFileOverwrite(filePath, options = {}) {
  const { silent = false, defaultAction = 'prompt' } = options;

  if (!fs.existsSync(filePath)) {
    return 'write';
  }

  // If it's our generated file, safe to overwrite
  if (isGeneratedFile(filePath)) {
    if (!silent) {
      console.log(chalk.gray(`  Updating ${path.basename(filePath)} (previously generated)`));
    }
    return 'write';
  }

  // File exists and wasn't generated by us - prompt user
  if (defaultAction === 'skip') {
    return 'skip';
  }

  const relativePath = path.basename(filePath);
  console.log(chalk.yellow(`\n  ⚠️  ${relativePath} already exists and appears to be modified`));

  const { action } = await inquirer.prompt([
    {
      type: 'list',
      name: 'action',
      message: `What would you like to do with ${relativePath}?`,
      choices: [
        { name: 'Overwrite (replace with generated code)', value: 'write' },
        { name: 'Backup and overwrite (save old file as .backup)', value: 'backup' },
        { name: 'Skip (keep existing file)', value: 'skip' },
      ],
    },
  ]);

  return action;
}

/**
 * Write file with optional backup
 */
function writeFileWithBackup(filePath, content, action) {
  if (action === 'skip') {
    return null;
  }

  if (action === 'backup' && fs.existsSync(filePath)) {
    const backupPath = `${filePath}.backup`;
    fs.copyFileSync(filePath, backupPath);
    console.log(chalk.gray(`  Backed up to ${path.basename(backupPath)}`));
  }

  fs.writeFileSync(filePath, content, 'utf8');
  return filePath;
}

/**
 * Ensure directory exists
 */
function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

/**
 * Generate SHA256 hash of project path for identification
 * This is used to identify returning projects when registering with backend
 */
function generateProjectPathHash(projectPath) {
  const absolutePath = path.resolve(projectPath);
  return crypto.createHash('sha256').update(absolutePath).digest('hex');
}

module.exports = {
  GENERATED_HEADER,
  isGeneratedFile,
  checkFileOverwrite,
  writeFileWithBackup,
  ensureDir,
  generateProjectPathHash,
};
