/**
 * Prompt Utilities
 * Shared prompt helpers for consistent CLI UX
 * Auto-generated by @l4yercak3/cli
 */

const inquirer = require('inquirer');
const chalk = require('chalk');

/**
 * Show a menu with options and handle selection
 * Always includes an Exit option at the end
 *
 * @param {Object} options - Menu configuration
 * @param {string} options.message - Menu header message
 * @param {Array<{name: string, value: string}>} options.choices - Menu choices
 * @returns {Promise<string>} The selected action value
 */
async function showActionMenu(options) {
  const { message = 'What would you like to do?', choices = [] } = options;

  // Always include exit option at the end
  const menuChoices = [
    ...choices,
    new inquirer.Separator(),
    { name: 'Exit', value: 'exit' },
  ];

  const { action } = await inquirer.prompt([
    {
      type: 'list',
      name: 'action',
      message,
      choices: menuChoices,
    },
  ]);

  // Handle exit
  if (action === 'exit') {
    console.log(chalk.gray('\n  Goodbye!\n'));
    process.exit(0);
  }

  return action;
}

/**
 * Get the full list of available CLI commands as menu choices
 * @param {Object} context - Context for filtering options
 * @param {boolean} context.isLoggedIn - Whether user is logged in
 * @param {boolean} context.isInProject - Whether CLI is running in a project directory
 * @param {boolean} context.hasExistingConfig - Whether project already has L4YERCAK3 config
 */
function getCommandChoices(context = {}) {
  const { isLoggedIn = true, isInProject = false, hasExistingConfig = false } = context;

  const choices = [];

  // Project setup commands (when in a project)
  if (isInProject) {
    if (hasExistingConfig) {
      choices.push({
        name: 'Reconfigure project        l4yercak3 spread',
        value: 'spread',
      });
    } else {
      choices.push({
        name: 'Set up L4YERCAK3           l4yercak3 spread',
        value: 'spread',
      });
    }
  } else {
    choices.push({
      name: 'Initialize project         l4yercak3 spread',
      value: 'spread',
    });
  }

  // Always available commands (when logged in)
  if (isLoggedIn) {
    choices.push(
      { name: 'View account status        l4yercak3 status', value: 'status' },
      { name: 'Manage API keys            l4yercak3 api-keys', value: 'api-keys' },
      { name: 'Set up MCP server          l4yercak3 mcp-setup', value: 'mcp-setup' },
      { name: 'Check for updates          l4yercak3 upgrade', value: 'upgrade' },
      new inquirer.Separator(),
      { name: 'Log out                    l4yercak3 logout', value: 'logout' },
    );
  } else {
    choices.push(
      { name: 'Log in                     l4yercak3 login', value: 'login' },
      { name: 'Check for updates          l4yercak3 upgrade', value: 'upgrade' },
    );
  }

  return choices;
}

/**
 * Show main menu with all available commands
 * @param {Object} context - Context for menu options
 * @param {boolean} context.isLoggedIn - Whether user is logged in
 * @param {boolean} context.isInProject - Whether CLI is running in a project directory
 * @param {boolean} context.hasExistingConfig - Whether project already has L4YERCAK3 config
 * @returns {Promise<string>} The selected action value
 */
async function showMainMenu(context = {}) {
  const choices = getCommandChoices(context);

  return await showActionMenu({
    message: 'What would you like to do?',
    choices,
  });
}

/**
 * Show post-login menu with common actions
 * @param {Object} context - Context for menu options
 * @param {boolean} context.isInProject - Whether CLI is running in a project directory
 * @param {boolean} context.hasExistingConfig - Whether project already has L4YERCAK3 config
 */
async function showPostLoginMenu(context = {}) {
  return await showMainMenu({ ...context, isLoggedIn: true });
}

/**
 * Execute a menu action by calling the appropriate command handler
 * @param {string} action - The action to execute
 * @returns {Promise<void>}
 */
async function executeMenuAction(action) {
  console.log('');

  switch (action) {
    case 'spread': {
      const { handler } = require('../commands/spread');
      await handler();
      break;
    }
    case 'status': {
      const { handler } = require('../commands/status');
      await handler();
      break;
    }
    case 'api-keys': {
      const { handler } = require('../commands/api-keys');
      await handler();
      break;
    }
    case 'logout': {
      const { handler } = require('../commands/logout');
      await handler();
      break;
    }
    case 'login': {
      const { handler } = require('../commands/login');
      await handler();
      break;
    }
    case 'mcp-setup': {
      const { handler } = require('../commands/mcp-setup');
      await handler();
      break;
    }
    case 'upgrade': {
      const { handler } = require('../commands/upgrade');
      await handler();
      break;
    }
    default:
      // Unknown action, just return
      break;
  }
}

/**
 * Show menu and execute selected action
 * Convenience function that combines showMainMenu + executeMenuAction
 * @param {Object} context - Context for menu options
 * @returns {Promise<string>} The selected action value
 */
async function showMenuAndExecute(context = {}) {
  const action = await showMainMenu(context);
  await executeMenuAction(action);
  return action;
}

module.exports = {
  showActionMenu,
  showMainMenu,
  showPostLoginMenu,
  getCommandChoices,
  executeMenuAction,
  showMenuAndExecute,
};
